name = "Create Wasteland Industry"
author = "QIUWH"
version = "0.3.40"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18b4c43c6ae75d8057240d944119bdeceb6a069055e9fb20bc78eedcf0a5f109"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
