name = "Create Wasteland Industry"
author = "QIUWH"
version = "0.3.40"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3fe7e645d1a0abec16cdc117cf941bf23889b9c36b61e29b0ca71b98c415cda"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
