ServerEvents.recipes(event => {

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/sulfur_copper_catalyst")
    .priority(1).duration(40)
    .inputItems("2x tfmg:sulfur_dust", "kubejs:copper_powder")
    .outputItems("kubejs:sulfur_copper_catalyst")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/chlorine_copper_catalyst")
    .priority(1).duration(40)
    .inputItems("kubejs:copper_powder")
    .inputFluids("kubejs:chlorine 250")
    .outputItems("kubejs:chlorine_copper_catalyst")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/nickel_catalyst_from_powder")
    .priority(1).duration(40)
    .inputItems("2x kubejs:caustic_soda_powder", "kubejs:nickel_powder")
    .outputItems("kubejs:nickel_catalyst")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/nickel_catalyst_from_fluid")
    .priority(1).duration(40)
    .inputItems("kubejs:nickel_powder")
    .inputFluids("kubejs:caustic_soda 250")
    .outputItems("kubejs:nickel_catalyst")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/caustic_soda_fluid")
    .priority(0).duration(40)
    .inputItems("kubejs:caustic_soda_powder")
    .inputFluids("kubejs:distilled_water 125")
    .outputFluids("kubejs:caustic_soda 125")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/brine_fluid")
    .priority(0).duration(40)
    .inputItems("ratatouille:salt")
    .inputFluids("kubejs:distilled_water 125")
    .outputFluids("kubejs:brine 125")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/bittern_fluid_from_water")
    .priority(0).duration(40)
    .inputItems("kubejs:halite_powder")
    .inputFluids("minecraft:water 125")
    .outputFluids("kubejs:bittern 125")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/bittern_fluid_from_distilled_water")
    .priority(0).duration(40)
    .inputItems("kubejs:halite_powder")
    .inputFluids("kubejs:distilled_water 125")
    .outputFluids("kubejs:bittern 125")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/nitrate_solution_fluid")
    .priority(0).duration(40)
    .inputItems("tfmg:nitrate_dust")
    .inputFluids("kubejs:distilled_water 125")
    .outputFluids("kubejs:nitrate_solution 125")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/bioethanol_sugar")
    .priority(0).duration(40)
    .inputItems(["minecraft:sugar","createaddition:biomass"])
    .inputFluids("kubejs:distilled_water 250")
    .outputFluids("createaddition:bioethanol 250")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/bioethanol_syrup")
    .priority(0).duration(40)
    .inputItems("createaddition:biomass")
    .inputFluids(["kubejs:distilled_water 125", "kubejs:syrup 125"])
    .outputFluids("createaddition:bioethanol 250")

  event.recipes.cwi.mixing_vessel_mixing()
    .id("cwi:mixing_vessel/biodiesel_fluid")
    .priority(0).duration(40)
    .inputFluids(["createdieselgenerators:ethanol 50", "createdieselgenerators:plant_oil 50"])
    .outputFluids("createdieselgenerators:biodiesel 100")

})