// priority: 10

ServerEvents.recipes(event => {

// Type Remove

    event.remove({ type: 'createaddition:rolling' })
    event.remove({ type: 'create:pressing', output: '#cwi:sheets' })
    event.remove({ type: 'createdieselgenerators:wire_cutting' })
    event.remove({ type: 'createdieselgenerators:hammering' })
    event.remove({ type: 'createdieselgenerators:compression_molding' })
    event.remove({ type: 'createdieselgenerators:distillation' })

// Whole Mod Remove

    const modsToRemove = [
        'create_sa',
        'constructionwand',
        'ad_astra',
        'functionalstorage',
        'create_rns', 
        'rubberworks', 
        'ae2', 
        'appflux', 
        'advanced_ae',
        'sculkcatalyticchamber', 
        'expatternprovider', 
        'sgjourney',
        'sophisticatedbackpacks', 
        'createmetallurgy', 
        'biomancy',
        'clanginghowl', 
        'vintageimprovements'
    ]
    modsToRemove.forEach(mod => event.remove({ mod: mod }))

// All Recipe Id Remove

    const idsToRemove = [

    // Bits N Bobs

        'bits_n_bobs:item_application/chain_pulley_from_rope_pulley_using_deployer',
        'bits_n_bobs:item_application/chain_pulley_from_rope_pulley',
        'bits_n_bobs:splashing/weathered_girder',
        'bits_n_bobs:splashing/weathered_girder_strut',

    // Create

        'create:compacting/andesite_from_flint',
        'create:compacting/blaze_cake',
        'create:compacting/cake_mold',
        'create:compacting/chocolate',
        'create:compacting/diorite_from_flint',
        'create:compacting/granite_from_flint',
        'create:crafting/appliances/chain_from_zinc',
        'create:crafting/appliances/netherite_backtank',
        'create:crafting/appliances/netherite_backtank_from_netherite',
        'create:crafting/appliances/netherite_diving_boots',
        'create:crafting/appliances/netherite_diving_boots_from_netherite',
        'create:crafting/appliances/netherite_diving_helmet',
        'create:crafting/appliances/netherite_diving_helmet_from_netherite',
        'create:crafting/appliances/slime_ball',
        'create:crafting/curiosities/cake',
        'create:crafting/kinetics/attribute_filter',
        'create:crafting/kinetics/basin',
        'create:crafting/kinetics/belt_connector',
        'create:crafting/kinetics/brass_hand',
        'create:crafting/kinetics/crafter_slot_cover',
        'create:crafting/kinetics/depot',
        'create:crafting/kinetics/deployer',
        'create:crafting/kinetics/elevator_pulley',
        'create:crafting/kinetics/empty_blaze_burner',
        'create:crafting/kinetics/encased_chain_drive',
        'create:crafting/kinetics/encased_chain_drive_from_zinc',
        'create:crafting/kinetics/filter',
        'create:crafting/kinetics/fluid_tank',
        'create:crafting/kinetics/hose_pulley',
        'create:crafting/kinetics/item_drain',
        'create:crafting/kinetics/linear_chassis',
        'create:crafting/kinetics/mechanical_arm',
        'create:crafting/kinetics/mechanical_crafter',
        'create:crafting/kinetics/mechanical_drill',
        'create:crafting/kinetics/mechanical_mixer',
        'create:crafting/kinetics/mechanical_press',
        'create:crafting/kinetics/mechanical_pump',
        'create:crafting/kinetics/mechanical_saw',
        'create:crafting/kinetics/millstone',
        'create:crafting/kinetics/nixie_tube',
        'create:crafting/kinetics/nozzle',
        'create:crafting/kinetics/portable_storage_interface',
        'create:crafting/kinetics/propeller',
        'create:crafting/kinetics/radial_chassis',
        'create:crafting/kinetics/rope_pulley',
        'create:crafting/kinetics/sail_frame_from_conversion',
        'create:crafting/kinetics/schedule',
        'create:crafting/kinetics/smart_chute',
        'create:crafting/kinetics/spout',
        'create:crafting/kinetics/steam_engine',
        'create:crafting/kinetics/super_glue',
        'create:crafting/kinetics/whisk',
        'create:crafting/kinetics/white_sail',
        'create:crafting/kinetics/white_sail_from_conversion',
        'create:crafting/kinetics/windmill_bearing',
        'create:crafting/logistics/andesite_funnel',
        'create:crafting/logistics/andesite_tunnel',
        'create:crafting/logistics/brass_funnel',
        'create:crafting/logistics/brass_tunnel',
        'create:crafting/logistics/content_observer',
        'create:crafting/logistics/package_frogport',
        'create:crafting/logistics/packager',
        'create:crafting/materials/andesite_alloy',
        'create:crafting/materials/andesite_alloy_from_zinc',
        'create:crafting/materials/electron_tube',
        'create:crafting/materials/rose_quartz',
        'create:crafting/schematics/schematicannon',
        'create:crushing/diorite',
        'create:crushing/diorite_recycling',
        'create:crushing/gilded_blackstone',
        'create:crushing/gravel',
        'create:crushing/tuff',
        'create:crushing/tuff_recycling',
        'create:filling/blaze_cake',
        'create:filling/cake',
        'create:filling/cake_mold_filled',
        'create:filling/grass_block',
        'create:filling/gunpowder',
        'create:filling/honey_cake',
        'create:haunting/blackstone',
        'create:haunting/crimson_fungus',
        'create:haunting/glow_berries',
        'create:haunting/glow_ink_sac',
        'create:haunting/infested_chiseled_stone_bricks',
        'create:haunting/infested_cracked_stone_bricks',
        'create:haunting/infested_deepslate',
        'create:haunting/infested_mossy_stone_bricks',
        'create:haunting/infested_stone',
        'create:haunting/infested_stone_bricks',
        'create:haunting/lapis_recycling',
        'create:haunting/nether_brick',
        'create:haunting/soul_sand',
        'create:haunting/soul_soil',
        'create:haunting/warped_fungus',
        'create:industrial_iron_block_from_ingots_iron_stonecutting',
        'create:industrial_iron_block_from_iron_ingots_stonecutting',
        'create:item_application/andesite_casing_from_log',
        'create:item_application/andesite_casing_from_log_using_deployer',
        'create:item_application/andesite_casing_from_wood',
        'create:item_application/andesite_casing_from_wood_using_deployer',
        'create:item_application/brass_casing_from_log',
        'create:item_application/brass_casing_from_log_using_deployer',
        'create:item_application/brass_casing_from_wood',
        'create:item_application/brass_casing_from_wood_using_deployer',
        'create:item_application/copper_casing_from_log',
        'create:item_application/copper_casing_from_log_using_deployer',
        'create:item_application/copper_casing_from_wood',
        'create:item_application/copper_casing_from_wood_using_deployer',
        'create:mechanical_crafting/crushing_wheel',
        'create:mechanical_crafting/extendo_grip',
        'create:mechanical_crafting/wand_of_symmetry',
        'create:milling/andesite',
        'create:milling/calcite',
        'create:milling/charcoal',
        'create:milling/coal',
        'create:milling/cobblestone',
        'create:milling/dripstone_block',
        'create:milling/gravel',
        'create:milling/wheat_flour',
        'create:milling/granite',
        'create:mixing/andesite_alloy',
        'create:mixing/andesite_alloy_from_zinc',
        'create:mixing/brass_ingot',
        'create:mixing/cake_batter',
        'create:mixing/compat/ae2/fluix_crystal',
        'create:mixing/compost_residue',
        'create:mixing/lava_from_cobble',
        'create:mixing/organic_compost',
        'create:mixing/pulp',
        'create:mixing/salt',
        'create:mixing/tea',
        'create:mixing/cardboard_pulp',
        'create:pressing/sugar_cane',
        'create:pressing/calorite_ingot',
        'create:pressing/desh_ingot',
        'create:pressing/ostrum_ingot',
        'create:pressing/steel_ingot',
        'create:sequenced_assembly/precision_mechanism',
        'create:sequenced_assembly/sturdy_sheet',
        'create:sequenced_assembly/track',
        'create:smelting/bread',
        'create:smelting/scoria',
        'create:splashing/crushed_raw_copper',
        'create:splashing/crushed_raw_gold',
        'create:splashing/crushed_raw_iron',
        'create:splashing/crushed_raw_zinc',
        'create:splashing/gravel',
        'create:splashing/ice',
        'create:splashing/industrial_iron_block',
        'create:splashing/industrial_iron_window',
        'create:splashing/industrial_iron_window_pane',
        'create:splashing/red_sand',
        'create:splashing/sand',
        'create:splashing/soul_sand',
        'create:splashing/wheat_flour',

    // Create Connected

        'create_connected:crafting/kinetics/cross_connector',
        'create_connected:crafting/kinetics/empty_fan_catalyst',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_blasting',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_ending_dragon_head',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_ending_dragons_breath',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_enriched',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_freezing',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_haunting',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_sanding',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_seething',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_smoking',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_splashing',
        'create_connected:crafting/kinetics/empty_fan_catalyst_from_withering',
        'create_connected:crafting/kinetics/fluid_vessel',
        'create_connected:crafting/kinetics/inventory_access_port',
        'create_connected:crafting/kinetics/kinetic_bridge',
        'create_connected:filling/fan_blasting_catalyst',
        'create_connected:filling/fan_splashing_catalyst',
        'create_connected:item_application/blasting_catalyst_from_empty',
        'create_connected:item_application/haunting_catalyst_from_empty',
        'create_connected:item_application/smoking_catalyst_from_empty',
        'create_connected:item_application/splashing_catalyst_from_empty',
        'create_connected:sequenced_assembly/control_chip',
        'create_connected:crafting/kinetics/dashboard',

    // Create New Age

        'create_new_age:compacting/blank_circuit',
        'create_new_age:crushing/radioactive_thorium',
        'create_new_age:cutting/copper_wire',
        'create_new_age:cutting/overcharged_golden_wire',
        'create_new_age:cutting/overcharged_iron_wire',
        'create_new_age:deploying/copper_circuit',
        'create_new_age:energising/experience_bottle',
        'create_new_age:energising/overcharged_diamond',
        'create_new_age:energising/overcharged_gold',
        'create_new_age:energising/overcharged_golden_sheet',
        'create_new_age:energising/overcharged_iron',
        'create_new_age:energising/overcharged_iron_sheet',
        'create_new_age:mechanical_crafting/advanced_motor_extension',
        'create_new_age:mechanical_crafting/reactor_rod',
        'create_new_age:mechanical_crafting/reinforced_motor',
        'create_new_age:mixing/thorium',
        'create_new_age:pressing/overcharged_golden_sheet',
        'create_new_age:pressing/overcharged_iron_sheet',
        'create_new_age:sequenced_assembly/overcharged_diamond_wire',
        'create_new_age:shaped/electrical_connector',
        'create_new_age:shaped/electrical_connector_mirrored',

    // Create Chunk Loader

        'create_power_loader:crafting/empty_andesite_chunk_loader',
        'create_power_loader:crafting/empty_brass_chunk_loader',

    // Create Addition

        'createaddition:compacting/seed_oil',
        'createaddition:crafting/copper_spool',
        'createaddition:crafting/electrum_spool',
        'createaddition:crafting/festive_spool',
        'createaddition:crafting/gold_spool',
        'createaddition:crafting/large_connector_electrum',
        'createaddition:crafting/large_connector_gold',
        'createaddition:crafting/rolling_mill',
        'createaddition:crafting/small_connector_copper',
        'createaddition:crafting/spool',
        'createaddition:crushing/diamond',
        'createaddition:liquid_burning/diesel',
        'createaddition:liquid_burning/gasoline',
        'createaddition:liquid_burning/lava',
        'createaddition:liquid_burning/plantoil',
        'createaddition:mechanical_crafting/alternator',
        'createaddition:mechanical_crafting/electric_motor',
        'createaddition:mechanical_crafting/tesla_coil',
        'createaddition:mixing/bioethanol',
        'createaddition:mixing/biomass_from_crops',
        'createaddition:mixing/biomass_from_flowers',
        'createaddition:mixing/biomass_from_honeycomb',
        'createaddition:mixing/biomass_from_leaves',
        'createaddition:mixing/biomass_from_plant_foods',
        'createaddition:mixing/biomass_from_plants',
        'createaddition:mixing/biomass_from_saplings',
        'createaddition:mixing/biomass_from_sticks',
        'createaddition:rolling/straw',

    // Create Deco

        'createdeco:compacting/industrial_iron_ingot',
        'createdeco:pressing/andesite_sheet',
        'createdeco:pressing/netherite_sheet',
        'createdeco:pressing/zinc_sheet',

    // Create Diesel Generator

        'createdieselgenerators:basin_fermenting/dough',
        'createdieselgenerators:basin_fermenting/fermentable',
        'createdieselgenerators:basin_fermenting/fermented_spider_eye',
        'createdieselgenerators:basin_fermenting/magma_cream',
        'createdieselgenerators:bulk_fermenting/fermentable',
        'createdieselgenerators:bulk_fermenting/lava',
        'createdieselgenerators:bulk_fermenting/magma_cream',
        'createdieselgenerators:bulk_fermenting/pulp',
        'createdieselgenerators:casting/chocolate_bar',
        'createdieselgenerators:compat/createaddition/copper_rod',
        'createdieselgenerators:compat/createaddition/electrum_rod',
        'createdieselgenerators:compat/createaddition/electrum_sheet',
        'createdieselgenerators:compat/createaddition/gold_rod',
        'createdieselgenerators:compat/createaddition/iron_rod',
        'createdieselgenerators:compat/createaddition/zinc_sheet',
        'createdieselgenerators:crafting/asphalt_block',
        'createdieselgenerators:crafting/asphalt_slab',
        'createdieselgenerators:crafting/asphalt_stairs',
        'createdieselgenerators:crafting/basin_lid',
        'createdieselgenerators:crafting/bulk_fermenter',
        'createdieselgenerators:crafting/burner',
        'createdieselgenerators:crafting/canister',
        'createdieselgenerators:crafting/chip_wood_beam',
        'createdieselgenerators:crafting/diesel_engine',
        'createdieselgenerators:crafting/distillation_controller',
        'createdieselgenerators:crafting/engine_piston',
        'createdieselgenerators:crafting/engine_piston_from_rods',
        'createdieselgenerators:crafting/engine_silencer',
        'createdieselgenerators:crafting/engine_turbocharger',
        'createdieselgenerators:crafting/hammer',
        'createdieselgenerators:crafting/huge_diesel_engine',
        'createdieselgenerators:crafting/kelp_handle',
        'createdieselgenerators:crafting/large_diesel_engine',
        'createdieselgenerators:crafting/oil_barrel',
        'createdieselgenerators:crafting/oil_scanner',
        'createdieselgenerators:crafting/pumpjack_bearing',
        'createdieselgenerators:crafting/pumpjack_head',
        'createdieselgenerators:crafting/pumpjack_hole',
        'createdieselgenerators:crushing/wood_chip_sticks',
        'createdieselgenerators:cutting/bar_mold',
        'createdieselgenerators:cutting/bowl_mold',
        'createdieselgenerators:cutting/chain_mold',
        'createdieselgenerators:cutting/lines_mold',
        'createdieselgenerators:cutting/wood_chips',
        'createdieselgenerators:mechanical_crafting/chemcial_sprayer',
        'createdieselgenerators:mechanical_crafting/pumpjack_crank',
        'createdieselgenerators:mixing/asphalt_block',
        'createdieselgenerators:mixing/biodiesel',
        'createdieselgenerators:stonecutting/asphalt_slab',
        'createdieselgenerators:stonecutting/asphalt_stairs',

    // Create Fishery Industry

        'createfisheryindustry:pressing/zinc_ingot',

    // Darker Depths

        'darkerdepths:amber',
        'darkerdepths:amber_block',
        'darkerdepths:darkslate',
        'darkerdepths:death_anchor',
        'darkerdepths:duskrock',
        'darkerdepths:forsaken_bronze_ingot_from_scrap',
        'darkerdepths:glow_ink_sac_from_glow_grime',
        'darkerdepths:grimestone',
        'darkerdepths:magma_pad',
        'darkerdepths:porous_petrified_log',
        'darkerdepths:rope',
        'darkerdepths:scorched_remains_block',
        'darkerdepths:void_soul_torch',

    // Farmers Delight

        'farmersdelight:bread_from_smelting',
        'farmersdelight:bread_from_smoking',
        'farmersdelight:cooking_pot',
        'farmersdelight:cutting/chicken',
        'farmersdelight:cutting/cod',
        'farmersdelight:cutting/cooked_chicken',
        'farmersdelight:cutting/cooked_cod',
        'farmersdelight:cutting/cooked_salmon',
        'farmersdelight:cutting/deepslate',
        'farmersdelight:cutting/gravel',
        'farmersdelight:cutting/salmon',
        'farmersdelight:cutting/stone',
        'farmersdelight:diamond_knife',
        'farmersdelight:gold_nugget_from_blasting_knife',
        'farmersdelight:gold_nugget_from_smelting_knife',
        'farmersdelight:golden_knife',
        'farmersdelight:iron_knife',
        'farmersdelight:iron_nugget_from_blasting_knife',
        'farmersdelight:iron_nugget_from_smelting_knife',
        'farmersdelight:netherite_knife_smithing',
        'farmersdelight:organic_compost_from_rotten_flesh',
        'farmersdelight:organic_compost_from_tree_bark',
        'farmersdelight:packed_mud_from_straw',
        'farmersdelight:cake_from_milk_bottle',
        'farmersdelight:paper_from_tree_bark',

    // Fluid

        'fluid:can_filler',
        'fluid:centrifugal_pump',
        'fluid:copper_sink',
        'fluid:copper_tap',
        'fluid:fluid_atomizer',
        'fluid:fluid_interface',
        'fluid:communicating_vessel',
        'fluid:freezing/blue_ice_from_packed_ice',
        'fluid:freezing/breeze_rod_from_blaze_rod',
        'fluid:freezing/packed_ice_from_ice',
        'fluid:freezing/slime_ball_from_magma_cream',
        'fluid:glueing/sticky_mechanical_piston',
        'fluid:glueing/sticky_piston',
        'fluid:haunting/haunting_fluid_bucket_from_slime_fluid_bucket',
        'fluid:mechanical_crafting/baton',
        'fluid:mechanical_pipette',
        'fluid:mixing/slime_fluid_from_slime_ball',
        'fluid:redstone_triple_valve',
        'fluid:redstone_valve',
        'fluid:smart_fluid_interface',
        'fluid:fluid_manifest',
        'fluid:smart_gutter_outlet',

    // Ftb Quest

        'ftbquests:loot_crate_opener',

    // Geode Plus

        'geode_plus:nether_quartz_crystal_block',

    // Multiblocked2

        'mbd2:mbd_gadgets',

    // Miners Delight

        'miners_delight:copper_pot',
        'miners_delight:string_from_gossypium',

    // Minecraft

        'minecraft:andesite',
        'minecraft:anvil',
        'minecraft:beacon',
        'minecraft:blast_furnace',
        'minecraft:blue_ice',
        'minecraft:bone_block',
        'minecraft:bread',
        'minecraft:brewing_stand',
        'minecraft:paper',
        'minecraft:cake',
        'minecraft:cauldron',
        'minecraft:chain',
        'minecraft:charcoal',
        'minecraft:coarse_dirt',
        'minecraft:copper_ingot_from_waxed_copper_block',
        'minecraft:crafting_table',
        'minecraft:diamond_axe',
        'minecraft:diamond_boots',
        'minecraft:diamond_chestplate',
        'minecraft:diamond_crystal_block_to_diamond',
        'minecraft:diamond_helmet',
        'minecraft:diamond_hoe',
        'minecraft:diamond_leggings',
        'minecraft:diamond_pickaxe',
        'minecraft:diamond_shovel',
        'minecraft:diamond_sword',
        'minecraft:diorite',
        'minecraft:dispenser',
        'minecraft:dropper',
        'minecraft:enchanting_table',
        'minecraft:ender_eye',
        'minecraft:fermented_spider_eye',
        'minecraft:furnace',
        'minecraft:glass',
        'minecraft:glass_pane',
        'minecraft:gold_nugget_from_blasting',
        'minecraft:gold_nugget_from_smelting',
        'minecraft:golden_axe',
        'minecraft:golden_boots',
        'minecraft:golden_chestplate',
        'minecraft:golden_helmet',
        'minecraft:golden_hoe',
        'minecraft:golden_leggings',
        'minecraft:golden_pickaxe',
        'minecraft:golden_shovel',
        'minecraft:golden_sword',
        'minecraft:granite',
        'minecraft:hopper',
        'minecraft:stick',
        'minecraft:iron_axe',
        'minecraft:iron_boots',
        'minecraft:iron_chestplate',
        'minecraft:iron_helmet',
        'minecraft:iron_hoe',
        'minecraft:iron_leggings',
        'minecraft:iron_nugget_from_blasting',
        'minecraft:iron_nugget_from_smelting',
        'minecraft:iron_pickaxe',
        'minecraft:iron_shovel',
        'minecraft:iron_sword',
        'minecraft:kjs/stonecutter',
        'minecraft:leather',
        'minecraft:magma_block',
        'minecraft:minecart',
        'minecraft:netherite_axe_smithing',
        'minecraft:netherite_boots_smithing',
        'minecraft:netherite_chestplate_smithing',
        'minecraft:netherite_helmet_smithing',
        'minecraft:netherite_hoe_smithing',
        'minecraft:netherite_leggings_smithing',
        'minecraft:netherite_pickaxe_smithing',
        'minecraft:netherite_scrap_from_blasting',
        'minecraft:netherite_shovel_smithing',
        'minecraft:netherite_sword_smithing',
        'minecraft:observer',
        'minecraft:packed_ice',
        'minecraft:piston',
        'minecraft:quartz_block',
        'minecraft:sandstone',
        'minecraft:shears',
        'minecraft:shield',
        'minecraft:smoker',
        'minecraft:stick_from_bamboo_item',
        'minecraft:sticky_piston',
        'minecraft:stone_axe',
        'minecraft:stone_hoe',
        'minecraft:stone_pickaxe',
        'minecraft:stone_shovel',
        'minecraft:stone_sword',
        'minecraft:stonecutter',
        'minecraft:sugar_from_honey_bottle',
        'minecraft:tinted_glass',
        'minecraft:lead',

    // Natures Compass

        'naturescompass:natures_compass',

    // Ratatouille

        'ratatouille:composting/composting',
        'ratatouille:composting/fermented_spider_eye',
        'ratatouille:composting/leather',
        'ratatouille:composting/more_dough',
        'ratatouille:composting/slime_ball',
        'ratatouille:demolding/cake_mold_baked',
        'ratatouille:eggshell',
        'ratatouille:mechanical_demolder',
        'ratatouille:organic_compost',
        'ratatouille:oven',
        'ratatouille:smoking/cake_mold_baked',
        'ratatouille:threshing/boil_stone',

    // Rustic Delight

        'rusticdelight:cooked_calamari',
        'rusticdelight:cooked_calamari_from_campfire_cooking',
        'rusticdelight:cooked_calamari_from_smoking',
        'rusticdelight:cooked_calamari_slice',
        'rusticdelight:cooked_calamari_slice_from_campfire_cooking',
        'rusticdelight:cooked_calamari_slice_from_smoking',
        'rusticdelight:cutting/calamari_slice',
        'rusticdelight:cutting/cooked_calamari_slice',
        'rusticdelight:string_from_cotton_boll',
        'rusticdelight:paper_from_cotton_boll',

    // Tfmg

        'tfmg:aluminum_wire_from_ingots_aluminum_stonecutting',
        'tfmg:blasting/lead_ingot_blasting',
        'tfmg:blasting/lithium_ingot_blasting',
        'tfmg:blasting/nickel_ingot_blasting',
        'tfmg:casting/cinderblock',
        'tfmg:casting/plastic_sheet',
        'tfmg:casting/silicon',
        'tfmg:casting/slag_block',
        'tfmg:casting/steel',
        'tfmg:coking/charcoal',
        'tfmg:coking/coal',
        'tfmg:compacting/cast_iron',
        'tfmg:constantan_wire_from_ingots_constantan_stonecutting',
        'tfmg:copper_wire_from_ingots_copper_stonecutting',
        'tfmg:crafting/kinetics/accumulator',
        'tfmg:crafting/kinetics/accumulatorfrom_lithium',
        'tfmg:crafting/kinetics/air_intake',
        'tfmg:crafting/kinetics/aluminum_fluid_tank',
        'tfmg:crafting/kinetics/aluminum_lamp',
        'tfmg:crafting/kinetics/aluminum_mechanical_pump',
        'tfmg:crafting/kinetics/black_multimeter',
        'tfmg:crafting/kinetics/blast_furnace_hatch',
        'tfmg:crafting/kinetics/blast_furnace_output',
        'tfmg:crafting/kinetics/blast_furnace_reinforcement',
        'tfmg:crafting/kinetics/blast_stove',
        'tfmg:crafting/kinetics/blue_multimeter',
        'tfmg:crafting/kinetics/brass_mechanical_pump',
        'tfmg:crafting/kinetics/brown_multimeter',
        'tfmg:crafting/kinetics/cable_tube',
        'tfmg:crafting/kinetics/cast_iron_chemical_vat',
        'tfmg:crafting/kinetics/cast_iron_fluid_tank',
        'tfmg:crafting/kinetics/cast_iron_mechanical_pump',
        'tfmg:crafting/kinetics/casting_basin',
        'tfmg:crafting/kinetics/circular_light',
        'tfmg:crafting/kinetics/coke_oven',
        'tfmg:crafting/kinetics/concrete_hose',
        'tfmg:crafting/kinetics/converter',
        'tfmg:crafting/kinetics/cyan_multimeter',
        'tfmg:crafting/kinetics/diagonal_cable_block',
        'tfmg:crafting/kinetics/electric_diode',
        'tfmg:crafting/kinetics/electric_post',
        'tfmg:crafting/kinetics/electric_pump',
        'tfmg:crafting/kinetics/electrical_switch',
        'tfmg:crafting/kinetics/engine_gearbox',
        'tfmg:crafting/kinetics/green_multimeter',
        'tfmg:crafting/kinetics/large_pumpjack_hammer_connector',
        'tfmg:crafting/kinetics/large_pumpjack_hammer_head',
        'tfmg:crafting/kinetics/light_blue_multimeter',
        'tfmg:crafting/kinetics/light_bulb',
        'tfmg:crafting/kinetics/light_gray_multimeter',
        'tfmg:crafting/kinetics/lime_multimeter',
        'tfmg:crafting/kinetics/machine_input',
        'tfmg:crafting/kinetics/magenta_multimeter',
        'tfmg:crafting/kinetics/modern_light',
        'tfmg:crafting/kinetics/multimeter',
        'tfmg:crafting/kinetics/neon_tube',
        'tfmg:crafting/kinetics/orange_multimeter',
        'tfmg:crafting/kinetics/pink_multimeter',
        'tfmg:crafting/kinetics/plastic_block',
        'tfmg:crafting/kinetics/plastic_mechanical_pump',
        'tfmg:crafting/kinetics/plastic_sheet',
        'tfmg:crafting/kinetics/polarizer',
        'tfmg:crafting/kinetics/pumpjack_crank',
        'tfmg:crafting/kinetics/purple_multimeter',
        'tfmg:crafting/kinetics/radial_engine',
        'tfmg:crafting/kinetics/red_multimeter',
        'tfmg:crafting/kinetics/regular_engine',
        'tfmg:crafting/kinetics/rusted_blast_furnace_reinforcement',
        'tfmg:crafting/kinetics/segmented_display',
        'tfmg:crafting/kinetics/steel_chemical_vat',
        'tfmg:crafting/kinetics/steel_distillation_controller',
        'tfmg:crafting/kinetics/steel_fluid_tank',
        'tfmg:crafting/kinetics/steel_mechanical_pump',
        'tfmg:crafting/kinetics/surface_scanner',
        'tfmg:crafting/kinetics/traffic_light',
        'tfmg:crafting/kinetics/transformer',
        'tfmg:crafting/kinetics/turbine_engine',
        'tfmg:crafting/kinetics/voltage_observer',
        'tfmg:crafting/kinetics/voltmeter',
        'tfmg:crafting/kinetics/white_multimeter',
        'tfmg:crafting/kinetics/winding_machine',
        'tfmg:crafting/kinetics/yellow_multimeter',
        'tfmg:crafting/kinetics/aluminum_sword',
        'tfmg:crafting/kinetics/aluminum_axe',
        'tfmg:crafting/kinetics/aluminum_pickaxe',
        'tfmg:crafting/kinetics/aluminum_shovel',
        'tfmg:crafting/kinetics/aluminum_hoe',
        'tfmg:crafting/kinetics/steel_sword',
        'tfmg:crafting/kinetics/steel_axe',
        'tfmg:crafting/kinetics/steel_pickaxe',
        'tfmg:crafting/kinetics/steel_shovel',
        'tfmg:crafting/kinetics/steel_hoe',
        'tfmg:crafting/kinetics/lead_sword',
        'tfmg:crafting/kinetics/lead_axe',
        'tfmg:crafting/kinetics/lead_pickaxe',
        'tfmg:crafting/kinetics/lead_shovel',
        'tfmg:crafting/kinetics/lead_hoe',
        'tfmg:crafting/kinetics/steel_helmet',
        'tfmg:crafting/kinetics/steel_chestplate',
        'tfmg:crafting/kinetics/steel_leggings',
        'tfmg:crafting/kinetics/steel_boots',
        'tfmg:crushing/copper_sulfate',
        'tfmg:crushing/dirt',
        'tfmg:crushing/sulfur',
        'tfmg:distillation/crude_oil',
        'tfmg:distillation/crude_oil_light_distillation',
        'tfmg:distillation/crude_oil_no_naphtha',
        'tfmg:distillation/heavy_oil',
        'tfmg:distillation/heavy_oil_light_distillation',
        'tfmg:distillation/heavy_oil_no_naphtha',
        'tfmg:engine_cylinder',
        'tfmg:engine_cylinder_cheap',
        'tfmg:engine_cylinder_gas',
        'tfmg:engine_cylinder_spark_plug',
        'tfmg:industrial_blasting/silicon',
        'tfmg:industrial_blasting/steel',
        'tfmg:industrial_blasting/steel_from_dust',
        'tfmg:industrial_blasting/steel_from_raw_iron',
        'tfmg:item_application/heavy_machinery_casing',
        'tfmg:item_application/heavy_machinery_casing_using_deployer',
        'tfmg:item_application/steel_casing',
        'tfmg:item_application/steel_casing_using_deployer',
        'tfmg:large_pumpjack_hammer_part_from_storage_blocks_steel_stonecutting',
        'tfmg:mechanical_crafting/engine_controller',
        'tfmg:mechanical_crafting/large_engine',
        'tfmg:mechanical_crafting/quad_potato_cannon',
        'tfmg:mechanical_crafting/rotor',
        'tfmg:mechanical_crafting/simple_large_engine',
        'tfmg:mechanical_crafting/spark_plug',
        'tfmg:mechanical_crafting/stator',
        'tfmg:mixing/asphalt_mixture',
        'tfmg:mixing/concrete_mixture',
        'tfmg:mixing/constantan',
        'tfmg:mixing/gunpowder',
        'tfmg:mixing/thermite',
        'tfmg:rebar_from_ingots_steel_stonecutting',
        'tfmg:screw_from_ingots_steel_stonecutting',
        'tfmg:sequenced_assembly/generator',
        'tfmg:sequenced_assembly/motor',
        'tfmg:sequenced_assembly/potentiometer',
        'tfmg:sequenced_assembly/steel_mechanism',
        'tfmg:turbine_blade',
        'tfmg:vat_machine_recipe/aluminum',
        'tfmg:vat_machine_recipe/arc_furnace_steel',
        'tfmg:vat_machine_recipe/concrete',
        'tfmg:vat_machine_recipe/etched_circuit_board',
        'tfmg:vat_machine_recipe/naphtha',
        'tfmg:vat_machine_recipe/neon',
        'tfmg:vat_machine_recipe/plastic_from_ethylene',
        'tfmg:vat_machine_recipe/plastic_from_propylene',
        'tfmg:vat_machine_recipe/sulfuric_acid',
        'tfmg:winding/electromagnetic_coil',
        'tfmg:winding/resistor',

    // Vital Herbs

        'vital_herbs:teapot_recipe'

    ]
    idsToRemove.forEach(id => event.remove({ id: id }))

})