ServerEvents.recipes(event => {

// Fermento Mycetes
  event.recipes.modpack.incubating()
      .id("kubejs:incubating/fermento_mycetes/frugal")
      .priority(0)
      .duration(2400)
      .inputItems('kubejs:sterilized_frugal_fermento_mycetes_petri_dish')
      .outputItems('kubejs:cultured_frugal_fermento_mycetes_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/fermento_mycetes/prolific")
      .priority(0)
      .duration(3600)
      .inputItems('kubejs:sterilized_prolific_fermento_mycetes_petri_dish')
      .outputItems('kubejs:cultured_prolific_fermento_mycetes_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/fermento_mycetes/rapid")
      .priority(0)
      .duration(4800)
      .inputItems('kubejs:sterilized_rapid_fermento_mycetes_petri_dish')
      .outputItems('kubejs:cultured_rapid_fermento_mycetes_petri_dish')

// Acidolys Bacillus
  event.recipes.modpack.incubating()
      .id("kubejs:incubating/acidolys_bacillus/heap")
      .priority(0)
      .duration(2400)
      .inputItems('kubejs:sterilized_heap_acidolys_bacillus_petri_dish')
      .outputItems('kubejs:cultured_heap_acidolys_bacillus_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/acidolys_bacillus/efficient")
      .priority(0)
      .duration(3600)
      .inputItems('kubejs:sterilized_efficient_acidolys_bacillus_petri_dish')
      .outputItems('kubejs:cultured_efficient_acidolys_bacillus_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/acidolys_bacillus/specialized")
      .priority(0)
      .duration(4800)
      .inputItems('kubejs:sterilized_specialized_acidolys_bacillus_petri_dish')
      .outputItems('kubejs:cultured_specialized_acidolys_bacillus_petri_dish')

// Vulcan Thermus
  event.recipes.modpack.incubating()
      .id("kubejs:incubating/vulcan_thermus/crude")
      .priority(0)
      .duration(2400)
      .inputItems('kubejs:sterilized_crude_vulcan_thermus_petri_dish')
      .outputItems('kubejs:cultured_crude_vulcan_thermus_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/vulcan_thermus/thermogenic")
      .priority(0)
      .duration(3600)
      .inputItems('kubejs:sterilized_thermogenic_vulcan_thermus_petri_dish')
      .outputItems('kubejs:cultured_thermogenic_vulcan_thermus_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/vulcan_thermus/thermoelectric")
      .priority(0)
      .duration(4800)
      .inputItems('kubejs:sterilized_thermoelectric_vulcan_thermus_petri_dish')
      .outputItems('kubejs:cultured_thermoelectric_vulcan_thermus_petri_dish')

// Carbofusor Spirillum
  event.recipes.modpack.incubating()
      .id("kubejs:incubating/carbofusor_spirillum/coal_saver")
      .priority(0)
      .duration(2400)
      .inputItems('kubejs:sterilized_coal_saver_carbofusor_spirillum_petri_dish')
      .outputItems('kubejs:cultured_coal_saver_carbofusor_spirillum_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/carbofusor_spirillum/pressurized")
      .priority(0)
      .duration(3600)
      .inputItems('kubejs:sterilized_pressurized_carbofusor_spirillum_petri_dish')
      .outputItems('kubejs:cultured_pressurized_carbofusor_spirillum_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/carbofusor_spirillum/syngas_rich")
      .priority(0)
      .duration(4800)
      .inputItems('kubejs:sterilized_syngas_rich_carbofusor_spirillum_petri_dish')
      .outputItems('kubejs:cultured_syngas_rich_carbofusor_spirillum_petri_dish')

// Putrelys Sporogenes
  event.recipes.modpack.incubating()
      .id("kubejs:incubating/putrelys_sporogenes/saprophytic")
      .priority(0)
      .duration(2400)
      .inputItems('kubejs:sterilized_saprophytic_putrelys_sporogenes_petri_dish')
      .outputItems('kubejs:cultured_saprophytic_putrelys_sporogenes_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/putrelys_sporogenes/proteolytic")
      .priority(0)
      .duration(3600)
      .inputItems('kubejs:sterilized_proteolytic_putrelys_sporogenes_petri_dish')
      .outputItems('kubejs:cultured_proteolytic_putrelys_sporogenes_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/putrelys_sporogenes/cellulolytic")
      .priority(0)
      .duration(4800)
      .inputItems('kubejs:sterilized_cellulolytic_putrelys_sporogenes_petri_dish')
      .outputItems('kubejs:cultured_cellulolytic_putrelys_sporogenes_petri_dish')

// Nitrofix Rhizobium
  event.recipes.modpack.incubating()
      .id("kubejs:incubating/nitrofix_rhizobium/sugar_fed")
      .priority(0)
      .duration(2400)
      .inputItems('kubejs:sterilized_sugar_fed_nitrofix_rhizobium_petri_dish')
      .outputItems('kubejs:cultured_sugar_fed_nitrofix_rhizobium_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/nitrofix_rhizobium/phototrophic")
      .priority(0)
      .duration(3600)
      .inputItems('kubejs:sterilized_phototrophic_nitrofix_rhizobium_petri_dish')
      .outputItems('kubejs:cultured_phototrophic_nitrofix_rhizobium_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/nitrofix_rhizobium/nitrifiying")
      .priority(0)
      .duration(4800)
      .inputItems('kubejs:sterilized_nitrifiying_nitrofix_rhizobium_petri_dish')
      .outputItems('kubejs:cultured_nitrifiying_nitrofix_rhizobium_petri_dish')

// Crystallum Coccus
  event.recipes.modpack.incubating()
      .id("kubejs:incubating/crystallum_coccus/cheap_crystal")
      .priority(0)
      .duration(2400)
      .inputItems('kubejs:sterilized_cheap_crystal_crystallum_coccus_petri_dish')
      .outputItems('kubejs:cultured_cheap_crystal_crystallum_coccus_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/crystallum_coccus/fast_nucleating")
      .priority(0)
      .duration(3600)
      .inputItems('kubejs:sterilized_fast_nucleating_crystallum_coccus_petri_dish')
      .outputItems('kubejs:cultured_fast_nucleating_crystallum_coccus_petri_dish')

  event.recipes.modpack.incubating()
      .id("kubejs:incubating/crystallum_coccus/precision")
      .priority(0)
      .duration(4800)
      .inputItems('kubejs:sterilized_precision_crystallum_coccus_petri_dish')
      .outputItems('kubejs:cultured_precision_crystallum_coccus_petri_dish')

})