// Priority: 1

StartupEvents.registry('block', event => {

// Natural Block

    event.create('dead_leaves', 'falling')
        .soundType('glow_lichen')
        .hardness(0.3)
        .resistance(0.3)
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()

    event.create('pebbles', 'pressure_plate')
        .soundType('stone')
        .hardness(0.3)
        .resistance(0.3)
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        
    event.create('raw_soil')
        .soundType('mud')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('soaked_depleted_dirt')
        .soundType('gravel')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('wet_depleted_dirt')
        .soundType('gravel')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('depleted_dirt')
        .soundType('gravel')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('depleted_dirt_slab', 'slab')
        .soundType('gravel')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('ashen_depleted_dirt')
        .soundType('gravel')
        .hardness(1)
        .resistance(1)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('crystalized_phyllite')
        .soundType('stone')
        .hardness(3)
        .resistance(6)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('claystone_biological_sediment')
        .soundType('deepslate')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#B0965F')

    event.create('acidified_darkslate')
        .soundType('deepslate')
        .lightLevel(0.5)
        .hardness(4.5)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('wet_biological_sediment')
        .soundType('mud')
        .hardness(1)
        .resistance(1)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('dry_biological_sediment')
        .soundType('deepslate')
        .hardness(2)
        .resistance(2)
        .tagBlock('minecraft:mineable/pickaxe')
        .mapColor('#FF5500')

    event.create('decayed_waste_sand','falling')
        .soundType('sand')
        .hardness(1)
        .resistance(1)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/shovel')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('decayed_waste_sediment')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('ash_dirt','falling')
        .soundType('sand')
        .hardness(1)
        .resistance(1)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('ash_stone')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('dark_ash_stone')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('dark_ash_stone_coal')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('dark_ash_stone_quartz')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('scrap_block', 'cardinal')
        .soundType('metal')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
        .defaultCutout()

    event.create('small_scrap_block', 'cardinal')
        .soundType('metal')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .box(0, 0, 0, 16, 8, 16)
        .box(8, 8, 0, 16, 12, 8,)
        .box(8, 8, 8, 16, 10, 16)
        .notSolid()
        .redstoneConductor(false)
        .defaultCutout()

    event.create('compressed_stone')
        .soundType('stone')
        .hardness(3.5)
        .resistance(3.5)
        .requiresTool(true)
        .notSolid()
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

// Ores

    event.create('quartz_ore')
        .textureAll('kubejs:block/ores/quartz_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('sulfur_ore')
        .textureAll('kubejs:block/ores/sulfur_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('tin_ore')
        .textureAll('kubejs:block/ores/tin_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('silver_ore')
        .textureAll('kubejs:block/ores/silver_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('fluorite_ore')
        .textureAll('kubejs:block/ores/fluorite_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

// Deepslate Ores

    event.create('deepslate_tin_ore')
        .textureAll('kubejs:block/ores/deepslate_tin_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('deepslate_sulfur_ore')
        .textureAll('kubejs:block/ores/deepslate_sulfur_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('deepslate_silver_ore')
        .textureAll('kubejs:block/ores/deepslate_silver_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('deepslate_quartz_ore')
        .textureAll('kubejs:block/ores/deepslate_quartz_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('deepslate_fluorite_ore')
        .textureAll('kubejs:block/ores/deepslate_fluorite_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

// Industrial Blocks

    event.create('forming_fabric', 'cardinal')
        .soundType('wood')
        .hardness(1)
        .resistance(1)
        .mapColor('#FF5500')
        .box(0, 0, 0, 16, 2, 16)
        .tagBlock('minecraft:mineable/axe')
        .notSolid()
        .suffocating(false)
        .defaultCutout()

    event.create('wet_web', 'cardinal')
        .soundType('wood')
        .hardness(1)
        .resistance(1)
        .mapColor('#FF5500')
        .box(0, 0, 0, 16, 2, 16)
        .tagBlock('minecraft:mineable/axe')
        .notSolid()
        .suffocating(false)
        .defaultCutout()

    event.create('pressed_wet_web', 'cardinal')
        .soundType('wood')
        .hardness(1)
        .resistance(1)
        .mapColor('#FF5500')
        .box(0, 0, 0, 16, 2, 16)
        .tagBlock('minecraft:mineable/axe')
        .notSolid()
        .suffocating(false)
        .defaultCutout()

    event.create('dried_web', 'cardinal')
        .soundType('wood')
        .hardness(1)
        .resistance(1)
        .mapColor('#FF5500')
        .box(0, 0, 0, 16, 2, 16)
        .tagBlock('minecraft:mineable/axe')
        .notSolid()
        .suffocating(false)
        .defaultCutout()

    event.create('small_pile_of_shafts', 'cardinal')
        .soundType('metal')
        .hardness(2)
        .resistance(2)
        .mapColor('#FF5500')
        .box(0, 0, 0, 16, 8, 16)
        .tagBlock('minecraft:mineable/pickaxe')
        .model('kubejs:block/shaft_piles/small_pile_of_shafts')
        .notSolid()
        .suffocating(false)
        .defaultCutout()

    event.create('pile_of_shafts', 'cardinal')
        .soundType('metal')
        .hardness(2)
        .resistance(2)
        .mapColor('#FF5500')
        .box(0, 0, 0, 16, 14, 16)
        .tagBlock('minecraft:mineable/pickaxe')
        .model('kubejs:block/shaft_piles/pile_of_shafts')
        .notSolid()
        .suffocating(false)
        .defaultCutout()

    event.create('large_pile_of_shafts', 'cardinal')
        .soundType('metal')
        .hardness(2)
        .resistance(2)
        .mapColor('#FF5500')
        .tagBlock('minecraft:mineable/pickaxe')
        .model('kubejs:block/shaft_piles/large_pile_of_shafts')
        .notSolid()
        .suffocating(false)
        .defaultCutout()

    event.create('condensed_antimatter', 'cardinal')
        .soundType('amethyst')
        .hardness(0)
        .resistance(0)
        .mapColor('#FF5500')
        .notSolid()

    event.create('steel_armor_block')
        .textureAll('kubejs:block/steel_armor/steel_armor_block')
        .soundType('metal')
        .hardness(120)
        .resistance(2000)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .tagBlock('kubejs:unbreakable')
        .mapColor('#FF5500')

    event.create('steel_armor_penetrated')
        .textureAll('kubejs:block/steel_armor/steel_armor_penetrated')
        .soundType('metal')
        .hardness(100)
        .resistance(1600)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .tagBlock('kubejs:unbreakable')
        .mapColor('#FF5500')

    event.create('steel_armor_safe', 'cardinal')
        .soundType('metal')
        .hardness(120)
        .resistance(2000)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .tagBlock('kubejs:unbreakable')
        .mapColor('#FF5500')

    event.create('rusted_heavy_machinery_casing')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('rusted_industrial_aluminum_casing')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('andesite_machine', 'cardinal')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('precise_machine', 'cardinal')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
  
    event.create('heavy_machine', 'cardinal')
        .soundType('metal')
        .hardness(4)
        .resistance(4)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('sealed_wood')
        .soundType('wood')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('polished_sealed_wood')
        .soundType('wood')
        .hardness(2.5)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('quality_sealed_wood')
        .soundType('wood')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_quality_sealed_wood')
        .soundType('wood')
        .hardness(2.5)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('harden_wood')
        .soundType('wood')
        .hardness(3.5)
        .resistance(3.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_harden_wood')
        .soundType('wood')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_precise_machine', 'cardinal')
        .soundType('metal')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .box(0, 0, 0, 16, 10, 16)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_heavy_machine', 'cardinal')
        .soundType('metal')
        .hardness(4)
        .resistance(4)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_mechanical_arm_base', 'cardinal')
        .soundType('metal')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .box(0, 0, 0, 16, 10, 16)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('mechanical_arm_base', 'cardinal')
        .soundType('metal')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .box(0, 0, 0, 16, 10, 16)
        .box(3, 10, 3, 13, 14, 13)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_stirling_engine', 'cardinal')
        .soundType('metal')
        .hardness(3)
        .resistance(6)
        .requiresTool(true)
        .box(0, 0, 0, 16, 3, 16)
        .box(2, 3, 2, 14, 13, 16)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_diesel_engine', 'cardinal')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_large_diesel_engine', 'cardinal')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_huge_diesel_engine', 'cardinal')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .redstoneConductor(false)

    event.create('incomplete_heavy_machinery_casing')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(5)
        .resistance(5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_blast_furnace_reinforcement')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(5)
        .resistance(5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('weathered_glass')
        .soundType('glass')
        .hardness(0.8)
        .resistance(0.8)
        .requiresTool(true)
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()

    event.create('cracked_glass')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('devitrified_glass')
        .soundType('glass')
        .hardness(0.8)
        .resistance(0.8)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('pressed_glass_blank')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('quenched_glass_blank')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('heated_glass')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        .defaultTranslucent()

    event.create('ion_exchanged_glass_blank')
        .soundType('glass')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        .defaultTranslucent()

    event.create('quenched_tempered_glass_blank')
        .soundType('glass')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        .defaultTranslucent()

    event.create('tempered_glass')
        .soundType('glass')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()

    event.create('industrial_casing')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
  
    event.create('claystone_clump')
        .textureAll('kubejs:block/claystone_base_bottom')
        .soundType('deepslate')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#B0965F')

    event.create('claystone_base')
        .soundType('deepslate')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBoth('cwi:ores')
        .mapColor('#B0965F')

    event.create('incomplete_furnace')
        .soundType('stone')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#B0965F')
  
    event.create('incomplete_crafting_table')
        .soundType('stone')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#705948')

    event.create('mixer_head')
        .model('kubejs:block/mixer_head')
        .soundType('metal')
        .hardness(2)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
        .suffocating(false)
        .defaultCutout()

    event.create('incomplete_mixing_vessel')
        .soundType('metal')
        .model('kubejs:block/mixing_vessel')
        .hardness(2)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
        .suffocating(false)
        .defaultCutout()

    event.create('capping_head')
        .soundType('wool')
        .hardness(1)
        .resistance(1.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/axe')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
        .suffocating(false)
        .defaultCutout()
    
})