// priority: 1

StartupEvents.registry('block', event => {

//natural block

  event.create('raw_soil')
    .soundType('mud')
    .hardness(0.8)
    .resistance(0.8)
    .tagBlock('minecraft:mineable/shovel')
    .mapColor('#FF5500')

  event.create('soaked_depleted_dirt')
    .soundType('gravel')
    .hardness(0.8)
    .resistance(0.8)
    .tagBlock('minecraft:mineable/shovel')
    .mapColor('#FF5500')

  event.create('wet_depleted_dirt')
    .soundType('gravel')
    .hardness(0.8)
    .resistance(0.8)
    .tagBlock('minecraft:mineable/shovel')
    .mapColor('#FF5500')

  event.create('depleted_dirt')
    .soundType('gravel')
    .hardness(0.8)
    .resistance(0.8)
    .tagBlock('minecraft:mineable/shovel')
    .mapColor('#FF5500')

  event.create('ashen_depleted_dirt')
    .soundType('gravel')
    .hardness(1)
    .resistance(1)
    .tagBlock('minecraft:mineable/shovel')
    .mapColor('#FF5500')

  event.create('crystalized_phyllite')
    .soundType('stone')
    .hardness(3)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('claystone_biological_sediment')
    .soundType('deepslate')
    .hardness(2)
    .resistance(2)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#B0965F')

  event.create('acidified_darkslate')
    .soundType('deepslate')
    .lightLevel(0.5)
    .hardness(4.5)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('wet_biological_sediment')
    .soundType('mud')
    .hardness(1)
    .resistance(1)
    .tagBlock('minecraft:mineable/shovel')
    .mapColor('#FF5500')

  event.create('dry_biological_sediment')
    .soundType('deepslate')
    .hardness(2)
    .resistance(2)
    .tagBlock('minecraft:mineable/pickaxe')
    .mapColor('#FF5500')

  event.create('decayed_waste_sand','falling')
    .soundType('sand')
    .hardness(1)
    .resistance(1)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/shovel')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('decayed_waste_sediment')
    .soundType('deepslate')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('ash_dirt','falling')
    .soundType('sand')
    .hardness(1)
    .resistance(1)
    .tagBlock('minecraft:mineable/shovel')
    .mapColor('#FF5500')

  event.create('ash_stone')
    .soundType('stone')
    .hardness(2)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('dark_ash_stone')
    .soundType('stone')
    .hardness(2)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('dark_ash_stone_coal')
    .soundType('stone')
    .hardness(2)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('dark_ash_stone_quartz')
    .soundType('stone')
    .hardness(2)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('scrap_block')
    .soundType('stone')
    .hardness(2)
    .resistance(3)
    .requiresTool(true)
    .notSolid()
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('compressed_stone')
    .soundType('stone')
    .hardness(3.5)
    .resistance(3.5)
    .requiresTool(true)
    .notSolid()
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

//compound minerals

  event.create('cassiterite_ore')
    .stoneSoundType()
    .hardness(4)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('cooperite_ore')
    .soundType('ancient_debris')
    .hardness(6)
    .resistance(12)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

  event.create('chalcocite_ore')
    .stoneSoundType()
    .hardness(4.5)
    .resistance(8)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('magnesite_ore')
    .stoneSoundType()
    .hardness(2.5)
    .resistance(5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('magnetite_ore')
    .stoneSoundType()
    .hardness(5)
    .resistance(8)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('halite_ore')
    .soundType('calcite')
    .hardness(3)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('borax_ore')
    .soundType('tuff')
    .hardness(3)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('rutile_ore')
    .soundType('amethyst')
    .hardness(3)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('uraninite_ore')
    .soundType('amethyst')
    .hardness(3)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('chromite_ore')
    .stoneSoundType()
    .hardness(4)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('pentlandite_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

  event.create('sphalerite_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
    .mapColor('#FF5500')

//storage block

  event.create('polyethylene_block')
    .soundType('metal')
    .hardness(4)
    .resistance(4)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('polypropylene_block')
    .soundType('metal')
    .hardness(4)
    .resistance(4)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('polyvinyl_chloride_block')
    .soundType('metal')
    .hardness(4)
    .resistance(4)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('carbon_fiber_block')
    .stoneSoundType()
    .hardness(8)
    .resistance(12)
    .tagBlock('minecraft:mineable/axe')
    .mapColor('#FF5500')

  event.create('rubber_block')
    .soundType('wool')
    .hardness(2)
    .resistance(3)
    .tagBlock('minecraft:mineable/axe')
    .mapColor('#FF5500')

  event.create('industrial_rubber_block')
    .soundType('wool')
    .hardness(3)
    .resistance(4)
    .tagBlock('minecraft:mineable/axe')
    .mapColor('#FF5500')

  event.create('rusted_iron_block')
    .stoneSoundType()
    .hardness(4)
    .resistance(5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('bronze_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    
  event.create('raw_cobalt_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('cobalt_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('magnesium_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('compressed_experience_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('sturdy_sheet_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('charcoal_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
  
  event.create('raw_tin_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('tin_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('raw_silver_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('silver_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('molybdenum_block')
    .stoneSoundType()
    .hardness(5)
    .resistance(6)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

//ores

  event.create('quartz_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('sulfur_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('tin_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('silver_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

  event.create('cobalt_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

  event.create('fluorite_ore')
    .stoneSoundType()
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

//deepslate ores

  event.create('deepslate_tin_ore')
    .soundType('deepslate')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('deepslate_sulfur_ore')
    .soundType('deepslate')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('deepslate_silver_ore')
    .soundType('deepslate')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

  event.create('deepslate_quartz_ore')
    .soundType('deepslate')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('deepslate_cobalt_ore')
    .soundType('deepslate')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('deepslate_fluorite_ore')
    .soundType('deepslate')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

//industrial blocks

  event.create('condensed_antimatter')
    .soundType('amethyst')
    .hardness(0)
    .resistance(0)
    .mapColor('#FF5500')
    .notSolid()
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('steel_armor_block')
    .soundType('metal')
    .hardness(120)
    .resistance(2000)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('kubejs:unbreakable')
    .mapColor('#FF5500')

  event.create('steel_armor_penetrated')
    .soundType('metal')
    .hardness(100)
    .resistance(1600)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('kubejs:unbreakable')
    .mapColor('#FF5500')

  event.create('steel_armor_safe')
    .soundType('metal')
    .hardness(120)
    .resistance(2000)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('kubejs:unbreakable')
    .mapColor('#FF5500')
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('computer_heat_vent')
    .soundType('metal')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

  event.create('rusted_heavy_machinery_casing')
    .soundType('metal')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

  event.create('rusted_industrial_aluminum_casing')
    .soundType('metal')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .mapColor('#FF5500')

  event.create('andesite_machine')
    .soundType('metal')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('precise_machine')
    .soundType('metal')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))
  
  event.create('heavy_machine')
    .soundType('metal')
    .hardness(4)
    .resistance(4)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('sealed_wood')
    .soundType('wood')
    .hardness(2)
    .resistance(2)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('polished_sealed_wood')
    .soundType('wood')
    .hardness(2.5)
    .resistance(2.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('quality_sealed_wood')
    .soundType('wood')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('incomplete_quality_sealed_wood')
    .soundType('wood')
    .hardness(2.5)
    .resistance(2.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('harden_wood')
    .soundType('wood')
    .hardness(3.5)
    .resistance(3.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('incomplete_harden_wood')
    .soundType('wood')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')

  event.create('incomplete_precise_machine')
    .soundType('metal')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_heavy_machine')
    .soundType('metal')
    .hardness(4)
    .resistance(4)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_mechanical_arm_base')
    .soundType('metal')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('mechanical_arm_base')
    .soundType('metal')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_diesel_engine')
    .soundType('metal')
    .texture('particle', 'tfmg:block/heavy_machinery_casing')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_large_diesel_engine')
    .soundType('metal')
    .texture('particle', 'tfmg:block/heavy_machinery_casing')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_huge_diesel_engine')
    .soundType('metal')
    .texture('particle', 'tfmg:block/heavy_machinery_casing')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .redstoneConductor(false)
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_heavy_machinery_casing')
    .soundType('metal')
    .texture('particle', 'tfmg:block/heavy_machinery_casing')
    .hardness(5)
    .resistance(5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_blast_furnace_reinforcement')
    .soundType('metal')
    .texture('particle', 'tfmg:block/heavy_machinery_casing')
    .hardness(5)
    .resistance(5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('weathered_glass')
    .soundType('glass')
    .hardness(0.6)
    .resistance(0.6)
    .requiresTool(true)
    .mapColor('#FF5500')
    .suffocating(false)
    .redstoneConductor(false)
    .defaultCutout()

  event.create('broken_glass')
    .soundType('glass')
    .hardness(0.6)
    .resistance(0.6)
    .requiresTool(true)
    .mapColor('#FF5500')
    .suffocating(false)
    .redstoneConductor(false)
    .defaultCutout()

  event.create('cool_glass')
    .soundType('glass')
    .hardness(1)
    .resistance(1)
    .requiresTool(true)
    .mapColor('#FF5500')
    .suffocating(false)
    .redstoneConductor(false)
    .defaultCutout()

  event.create('reinforced_glass')
    .soundType('glass')
    .hardness(2)
    .resistance(2)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .suffocating(false)
    .redstoneConductor(false)
    .defaultCutout()

  event.create('annealed_glass')
    .soundType('glass')
    .hardness(4)
    .resistance(4)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .suffocating(false)
    .redstoneConductor(false)
    .defaultCutout()

  event.create('industrial_casing')
    .soundType('metal')
    .hardness(3)
    .resistance(4.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
  
  event.create('claystone_clump')
    .soundType('deepslate')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#B0965F')

  event.create('claystone_base')
    .soundType('deepslate')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#B0965F')

  event.create('incomplete_furnace')
    .soundType('stone')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#B0965F')
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))
  
  event.create('incomplete_crafting_table')
    .soundType('stone')
    .hardness(3)
    .resistance(3)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#705948')

  event.create('incubator_blade')
    .model('kubejs:block/incubator_blade_alone')
    .soundType('metal')
    .hardness(2)
    .resistance(2.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
    .suffocating(false)
    .defaultCutout()
	  .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))

  event.create('incomplete_incubator')
    .soundType('metal')
    .model('kubejs:block/incubator')
    .hardness(2)
    .resistance(2.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
    .suffocating(false)
    .defaultCutout()

  event.create('mixer_head')
    .model('kubejs:block/mixer_head')
    .soundType('metal')
    .hardness(2)
    .resistance(2.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
    .suffocating(false)
    .defaultCutout()

  event.create('incomplete_mixing_vessel')
    .soundType('metal')
    .model('kubejs:block/mixing_vessel')
    .hardness(2)
    .resistance(2.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_stone_tool')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
    .suffocating(false)
    .defaultCutout()

  event.create('capping_head')
    .soundType('wool')
    .hardness(1)
    .resistance(1.5)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/axe')
    .mapColor('#FF5500')
    .notSolid()
    .redstoneConductor(false)
    .suffocating(false)
    .defaultCutout()

})