// Priority: 1

StartupEvents.registry('block', event => {

// Natural Block

    event.create('dead_leaves', 'falling')
        .soundType('glow_lichen')
        .hardness(0.3)
        .resistance(0.3)
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        
    event.create('raw_soil')
        .soundType('mud')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('soaked_depleted_dirt')
        .soundType('gravel')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('wet_depleted_dirt')
        .soundType('gravel')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('depleted_dirt')
        .soundType('gravel')
        .hardness(0.8)
        .resistance(0.8)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('ashen_depleted_dirt')
        .soundType('gravel')
        .hardness(1)
        .resistance(1)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('crystalized_phyllite')
        .soundType('stone')
        .hardness(3)
        .resistance(6)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('claystone_biological_sediment')
        .soundType('deepslate')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#B0965F')

    event.create('acidified_darkslate')
        .soundType('deepslate')
        .lightLevel(0.5)
        .hardness(4.5)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('wet_biological_sediment')
        .soundType('mud')
        .hardness(1)
        .resistance(1)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('dry_biological_sediment')
        .soundType('deepslate')
        .hardness(2)
        .resistance(2)
        .tagBlock('minecraft:mineable/pickaxe')
        .mapColor('#FF5500')

    event.create('decayed_waste_sand','falling')
        .soundType('sand')
        .hardness(1)
        .resistance(1)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/shovel')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('decayed_waste_sediment')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('ash_dirt','falling')
        .soundType('sand')
        .hardness(1)
        .resistance(1)
        .tagBlock('minecraft:mineable/shovel')
        .mapColor('#FF5500')

    event.create('ash_stone')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('dark_ash_stone')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('dark_ash_stone_coal')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('dark_ash_stone_quartz')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wooden_tool')
        .mapColor('#FF5500')

    event.create('scrap_block')
        .soundType('stone')
        .hardness(2)
        .resistance(3)
        .requiresTool(true)
        .notSolid()
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('compressed_stone')
        .soundType('stone')
        .hardness(3.5)
        .resistance(3.5)
        .requiresTool(true)
        .notSolid()
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

// Storage Block

    const storageBlocks = [
        { name: 'polyethylene_block',        sound: 'metal', hardness: 4, resistance: 4,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'polypropylene_block',       sound: 'metal', hardness: 4, resistance: 4,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'polyvinyl_chloride_block',  sound: 'metal', hardness: 4, resistance: 4,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'carbon_fiber_block',        sound: 'stone', hardness: 8, resistance: 12, tool: 'axe',     needsTool: false, tier: null },
        { name: 'rubber_block',              sound: 'wool',  hardness: 2, resistance: 3,  tool: 'axe',     needsTool: false, tier: null },
        { name: 'industrial_rubber_block',   sound: 'wool',  hardness: 3, resistance: 4,  tool: 'axe',     needsTool: false, tier: null },
        { name: 'rusted_iron_block',         sound: 'stone', hardness: 4, resistance: 5,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'bronze_block',              sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'cobalt_block',              sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'magnesium_block',           sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'charcoal_block',            sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'raw_tin_block',             sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'tin_block',                 sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'raw_silver_block',          sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'silver_block',              sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'stone' },
        { name: 'molybdenum_block',          sound: 'stone', hardness: 5, resistance: 6,  tool: 'pickaxe', needsTool: true,  tier: 'iron' }
    ]

    storageBlocks.forEach(function(block) {
        var builder = event.create(block.name)
            .textureAll('kubejs:block/storage_blocks/' + block.name)
            .hardness(block.hardness)
            .resistance(block.resistance)
            .mapColor('#FF5500')
            .tagBlock('minecraft:mineable/' + block.tool)
        if (block.sound === 'metal') builder.soundType('metal')
        else if (block.sound === 'wool') builder.soundType('wool')
        else if (block.sound === 'stone') builder.stoneSoundType()
        if (block.needsTool) builder.requiresTool(true)
        if (block.tier) builder.tagBlock('minecraft:needs_' + block.tier + '_tool')
    })

// Ores

    event.create('quartz_ore')
        .textureAll('kubejs:block/ores/quartz_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('sulfur_ore')
        .textureAll('kubejs:block/ores/sulfur_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('tin_ore')
        .textureAll('kubejs:block/ores/tin_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('silver_ore')
        .textureAll('kubejs:block/ores/silver_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('fluorite_ore')
        .textureAll('kubejs:block/ores/fluorite_ore')
        .stoneSoundType()
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

// Deepslate Ores

    event.create('deepslate_tin_ore')
        .textureAll('kubejs:block/ores/deepslate_tin_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('deepslate_sulfur_ore')
        .textureAll('kubejs:block/ores/deepslate_sulfur_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('deepslate_silver_ore')
        .textureAll('kubejs:block/ores/deepslate_silver_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('deepslate_quartz_ore')
        .textureAll('kubejs:block/ores/deepslate_quartz_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('deepslate_fluorite_ore')
        .textureAll('kubejs:block/ores/deepslate_fluorite_ore')
        .soundType('deepslate')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

// Industrial Blocks

    event.create('condensed_antimatter')
        .soundType('amethyst')
        .hardness(0)
        .resistance(0)
        .mapColor('#FF5500')
        .notSolid()

    event.create('steel_armor_block')
        .textureAll('kubejs:block/steel_armor/steel_armor_block')
        .soundType('metal')
        .hardness(120)
        .resistance(2000)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .tagBlock('kubejs:unbreakable')
        .mapColor('#FF5500')

    event.create('steel_armor_penetrated')
        .textureAll('kubejs:block/steel_armor/steel_armor_penetrated')
        .soundType('metal')
        .hardness(100)
        .resistance(1600)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .tagBlock('kubejs:unbreakable')
        .mapColor('#FF5500')

    event.create('steel_armor_safe')
        .soundType('metal')
        .hardness(120)
        .resistance(2000)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .tagBlock('kubejs:unbreakable')
        .mapColor('#FF5500')

    event.create('rusted_heavy_machinery_casing')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('rusted_industrial_aluminum_casing')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .mapColor('#FF5500')

    event.create('andesite_machine')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('precise_machine')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
  
    event.create('heavy_machine')
        .soundType('metal')
        .hardness(4)
        .resistance(4)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('sealed_wood')
        .soundType('wood')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('polished_sealed_wood')
        .soundType('wood')
        .hardness(2.5)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('quality_sealed_wood')
        .soundType('wood')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_quality_sealed_wood')
        .soundType('wood')
        .hardness(2.5)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('harden_wood')
        .soundType('wood')
        .hardness(3.5)
        .resistance(3.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_harden_wood')
        .soundType('wood')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_precise_machine')
        .soundType('metal')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_heavy_machine')
        .soundType('metal')
        .hardness(4)
        .resistance(4)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_mechanical_arm_base')
        .soundType('metal')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('mechanical_arm_base')
        .soundType('metal')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_diesel_engine')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_large_diesel_engine')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)

    event.create('incomplete_huge_diesel_engine')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .redstoneConductor(false)

    event.create('incomplete_heavy_machinery_casing')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(5)
        .resistance(5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('incomplete_blast_furnace_reinforcement')
        .soundType('metal')
        .texture('particle', 'tfmg:block/heavy_machinery_casing')
        .hardness(5)
        .resistance(5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')

    event.create('weathered_glass')
        .soundType('glass')
        .hardness(0.8)
        .resistance(0.8)
        .requiresTool(true)
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()

    event.create('cracked_glass')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('devitrified_glass')
        .soundType('glass')
        .hardness(0.8)
        .resistance(0.8)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('pressed_glass_blank')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('quenched_glass_blank')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')

    event.create('heated_glass')
        .soundType('glass')
        .hardness(0.6)
        .resistance(0.6)
        .requiresTool(true)
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        .defaultTranslucent()

    event.create('ion_exchanged_glass_blank')
        .soundType('glass')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        .defaultTranslucent()

    event.create('quenched_tempered_glass_blank')
        .soundType('glass')
        .hardness(2)
        .resistance(2)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()
        .defaultTranslucent()

    event.create('tempered_glass')
        .soundType('glass')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .suffocating(false)
        .redstoneConductor(false)
        .defaultCutout()

    event.create('industrial_casing')
        .soundType('metal')
        .hardness(3)
        .resistance(4.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
  
    event.create('claystone_clump')
        .textureAll('kubejs:block/claystone_base_bottom')
        .soundType('deepslate')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#B0965F')

    event.create('claystone_base')
        .soundType('deepslate')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .tagBoth('cwi:ores')
        .mapColor('#B0965F')

    event.create('incomplete_furnace')
        .soundType('stone')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#B0965F')
  
    event.create('incomplete_crafting_table')
        .soundType('stone')
        .hardness(3)
        .resistance(3)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#705948')

    event.create('mixer_head')
        .model('kubejs:block/mixer_head')
        .soundType('metal')
        .hardness(2)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
        .suffocating(false)
        .defaultCutout()

    event.create('incomplete_mixing_vessel')
        .soundType('metal')
        .model('kubejs:block/mixing_vessel')
        .hardness(2)
        .resistance(2.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_stone_tool')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
        .suffocating(false)
        .defaultCutout()

    event.create('capping_head')
        .soundType('wool')
        .hardness(1)
        .resistance(1.5)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/axe')
        .mapColor('#FF5500')
        .notSolid()
        .redstoneConductor(false)
        .suffocating(false)
        .defaultCutout()
    
})