#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 22 20:44:06 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=BSL_v8.4.zip
enableShaders=false
