#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 18 20:22:39 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Mellow Shader v3.2.zip
enableShaders=false
