#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 28 23:41:43 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Mellow Shader v3.1.1.zip
enableShaders=true
